## * /////////////////////////////////////////////////////////////////////////////////////////////
## *
## * FileName     [ docker-compose.yml ]
## * PackageName  [ tools ]
## * Synopsis     [ Ymls file for composing docker containers ]
## * Author       [ Chin-Yi Cheng ]
## * Copyright    [ 2022 9 ]
## * 
## * /////////////////////////////////////////////////////////////////////////////////////////////

version: "3.4"
name: "dvlab-prod"
services:
  frontend:
    restart: always
    build:
      context: ${PWD}
      dockerfile: ./tools/Dockerfile.frontend
  backend:
    restart: always
    build:
      context: ${PWD}
      dockerfile: ./tools/Dockerfile.backend
  nginx:
    image: jonasal/nginx-certbot:3
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=dvlabdvlab@gmail.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./tools/letsencrypt:/etc/letsencrypt
      - ./tools/user_conf.d:/etc/nginx/user_conf.d
