## * /////////////////////////////////////////////////////////////////////////////////////////////
## *
## * FileName     [ Dockerfile ]
## * PackageName  [ nginx ]
## * Synopsis     [ Create nginx docker image and container ]
## * Author       [ Chin-Yi Cheng ]
## * Copyright    [ 2022 9 ]
## * 
## * /////////////////////////////////////////////////////////////////////////////////////////////

FROM nginx:stable

WORKDIR /app

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
