FROM node:16-buster

# setup working directory
WORKDIR /app

# install node_modules in the container
COPY ["backend/package.json", "backend/yarn.lock", "./"]
RUN yarn

COPY ./backend .

EXPOSE 4000

# startup command
CMD ["yarn", "run", "server"] 