## * /////////////////////////////////////////////////////////////////////////////////////////////
## *
## * FileName     [ Dockerfile.backend ]
## * PackageName  [ tools ]
## * Synopsis     [ Create backend docker image and container ]
## * Author       [ Chin-Yi Cheng ]
## * Copyright    [ 2022 9 ]
## * 
## * /////////////////////////////////////////////////////////////////////////////////////////////

FROM node:16-buster

# setup working directory
WORKDIR /app

# install node_modules in the container
COPY ["frontend/package.json", "frontend/yarn.lock", "./"]
RUN yarn

COPY ./frontend .

# build
RUN yarn

# react-scripts run on port 3000
EXPOSE 3000
# startup command
CMD ["yarn", "start"] 
