## * /////////////////////////////////////////////////////////////////////////////////////////////
## *
## * FileName     [ docker-compose.yml ]
## * PackageName  [ tools ]
## * Synopsis     [ Ymls file for composing docker containers ]
## * Author       [ Chin-Yi Cheng ]
## * Copyright    [ 2022 9 ]
## * 
## * /////////////////////////////////////////////////////////////////////////////////////////////

version: "3.4"
name: "dvlab-prod"
services:
  frontend:
    build:
      context: ${PWD}
      dockerfile: ./tools/Dockerfile.frontend
  backend:
    build:
      context: ${PWD}
      dockerfile: ./tools/Dockerfile.backend
  nginx:
    build:
      context: ${PWD}
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ${PWD}/nginx:/etc/nginx/conf.d
